apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-deployment
  labels:
    app: aks
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aks
  template:
    metadata:
      labels:
        app: aks
    spec:
      containers:
      - name: aks
        image: cicdregistry12.azurecr.io/cicdregistry12:$(Build.BuildId)
        ports:
        - containerPort: 8080
